- add ufo audiogroup compressor (no dice)

diff --git a/ports/blungosdungeonluncheon/blungosdungeonluncheon/tools/patchscript b/ports/blungosdungeonluncheon/blungosdungeonluncheon/tools/patchscript
--- a/ports/blungosdungeonluncheon/blungosdungeonluncheon/tools/patchscript
+++ b/ports/blungosdungeonluncheon/blungosdungeonluncheon/tools/patchscript
@@ -1,10 +1,12 @@
 #!/bin/bash
 
-# set gamedir to the current directory and set log file
+# set gamedir to the current directory and set logfile
 GAMEDIR="$PWD"
 LOGFILE="$GAMEDIR/patchlog.txt"
+LOGERR="$GAMEDIR/patch_error.txt"
 
 # redirect output and error to the log file
+rm -rf $LOGFILE $LOGERR
 exec > >(tee -a "$LOGFILE") 2>&1
 echo "GAMEDIR is set to: $GAMEDIR"
 
@@ -15,25 +17,41 @@ export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/lib:$GAMEDIR/tools/libs:$LD_LIBRARY_PA
 export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
 export TOOLDIR="$GAMEDIR/tools"
 export TMPDIR="$GAMEDIR/tmp"
-export PATH="$controlfolder:$GAMEDIR/tools:$PATH"
+export PATH="$GAMEDIR/tools:$PATH"
 
 # permissions
 chmod 666 /dev/uinput
 chmod 777 "$TOOLDIR/gmKtool.py"
 chmod 777 "$TOOLDIR/oggenc"
-chmod 777 "$TOOLDIR/oggdec"
 
 cd "$GAMEDIR"
 
+unzip_audiogroups() {
+  # unzip from $DATAFILE into $DATADIR
+  echo "Unzipping ${DATAFILE}..."
+  mkdir -p assets
+  unzip -j -o "$DATAFILE" "assets/*.dat" -d "$DATADIR"
+  if [ $? -eq 0 ]; then
+    echo "Unzipped successfully to $DATADIR."
+  else
+    echo "Failed to unzip file."
+    mv $LOGFILE $LOGERR
+    exit 1
+  fi
+}
+
 compress_audio() {
-  echo "Compressing audio ..."
-  # clear out the temporary directory
   mkdir -p "$TMPDIR"
-  rm -rf $TMPDIR/*
 
   # run the compression tool
-  echo "Running GMTools on data and audiogroups."
-  $PYTHON $TOOLDIR/gmKtool.py -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"
+  PYTHON=$(which python3)
+  if [ "$PREPATCH" != 1 ]; then
+    echo "Running GMTools on data and audiogroups ..."
+    $PYTHON ./tools/gmKtool.py -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"
+  else
+    echo "Running GMTools on data file only ..."
+    $PYTHON ./tools/gmKtool.py -vv -O 0 -m 1000 -b 64 -r -d "$TMPDIR" "$DATADIR/game.droid"
+  fi
 
   if [ $? -eq 0 ]; then
     echo "Compression completed successfully."
@@ -42,41 +60,44 @@ compress_audio() {
     rm -rf "$TMPDIR"
     echo "Temporary directory $TMPDIR removed."
     echo "Audio compression applied successfully."
-    sleep 1
   else
     echo "Audio compression failed."
     echo "Cleaning up temporary directory $TMPDIR."
     rm -rf "$TMPDIR"
-    sleep 1
   fi
 }
 
 zip_archive() {
-  echo "Zip assets to $DATAFILE."
   zip -r -0 $DATAFILE ./assets/
-  echo "Delete assets folder."
-  #rm -Rf "$DATADIR/assets" -------------------- TEMP COMMENT TO CHECK AUDIOGROUP FILE SIZES
-}
-
-install_complete() {
-  # create install completion flag
-  touch "install_completed"
-  echo "Installation completed successfully!"
-  echo "-----------------------------"
-  echo "Process finished at: $(date)"
+  mkdir -p saves
+  rm -rf $DATADIR/*
 }
 
 process_game() {
+  # delete unnecessary files
+  rm -rf $DATADIR/*.exe $DATADIR/*.dll $DATADIR/.gitkeep
+  echo "Removed unnecessary files"
+
+  # check if we're using a prepatched game
+  if unzip -l "$DATAFILE" "assets/*" | grep -q "assets/.*\.dat"; then
+    echo "Prepatched game detected." && sleep 1
+    PREPATCH=1
+    unzip_audiogroups
+  fi
+
   echo "Rename data.win to game.droid ..."
   mv "$DATADIR/data.win" "$DATADIR/game.droid"
+  sleep 1
   echo "Compressing audio ..."
   compress_audio
   sleep 1
   echo "Finishing up ..."
   zip_archive
   sleep 1
-  install_complete
+
+  # final completion message
+  echo "Patching process complete!"
 }
 
-# call the function
+# Call the function
 process_game
